### ISSUE TITLE
Build fails in production (Vercel)

### ISSUE THREAD

**Issue by kamster94** [tinacms/tina-self-hosted-demo#113]
I used Deploy to Vercel button, followed all steps, but the build failed with following error:
```
14:50:11.857 | Starting Tina build
14:50:16.503 | Indexing to self-hosted data layer
14:50:28.322 | node:internal/deps/undici/undici:11576
14:50:28.322 | Error.captureStackTrace(err, this);
14:50:28.322 | ^
14:50:28.322 |  
14:50:28.322 | TypeError: fetch failed
14:50:28.322 | at Object.fetch (node:internal/deps/undici/undici:11576:11)
14:50:28.322 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
14:50:28.322 | at async ie.request (/tmp/1702129815641/database.build.js:57442:17)
14:50:28.323 | at async F.exec (/tmp/1702129815641/database.build.js:57521:39)
14:50:28.323 | at async RedisLevel2._get (/tmp/1702129815641/database.build.js:59677:25) {
14:50:28.323 | cause: Error: getaddrinfo ENOTFOUND wired-grizzly-48957.kv.vercel-storage.com
14:50:28.323 | at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:108:26) {
14:50:28.323 | errno: -3008,
14:50:28.323 | code: 'ENOTFOUND',
14:50:28.323 | syscall: 'getaddrinfo',
14:50:28.323 | hostname: 'wired-grizzly-48957.kv.vercel-storage.com'
14:50:28.323 | }
14:50:28.355 | }
14:50:28.355 |  
14:50:28.355 | Node.js v18.18.0
14:50:28.384 | error Command failed with exit code 1.
14:50:28.384 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
14:50:28.417 | Error: Command "yarn run build" exited with 1
```

**Comment by iassia** [comment]
@kamster94 Vercel had an issue with KV on 8 and 9 Dec as you can check here: https://www.vercel-status.com/#past-incidents

Try to redeploy your build, should be fine now 👍

**Comment by kamster94** [comment]
Yes, I can confirm it works now. Thanks for the info. Closing the issue.
